# Generated by Django 4.2.16 on 2024-09-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address_created_at_address_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="address",
            name="pin_code",
            field=models.CharField(max_length=6),
        ),
    ]
