# Generated by Django 5.0 on 2024-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="content",
            new_name="story",
        ),
    ]
