# Generated by Django 5.0 on 2024-10-25 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_teammember_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="legal",
            name="cancelation_policy",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinLengthValidator(500)],
            ),
        ),
    ]
