# Generated by Django 5.0 on 2024-10-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_legal_cancelation_policy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legal",
            old_name="cancelation_policy",
            new_name="cancellation_policy",
        ),
    ]
