# Generated by Django 5.1.1 on 2024-09-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_quote_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
