# Generated by Django 5.0 on 2024-09-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_category_image_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="category",
            name="quote",
            field=models.CharField(max_length=200),
        ),
    ]
